### ISSUE TITLE
[Feature Request] Sync CriCri with the b2022 fork

### ISSUE THREAD

**Issue by p4535992** [christianclavet/naps2-cricri-edition#5]
Hey Christian awesome job, with this fork , I saw that the original author on his branch b2022 (https://github.com/cyanfish/naps2/tree/b2022) is moving forward with the development.

Do you think it is possible to open a PR on that branch to merge your features in the original project ?

**Comment by christianclavet** [comment]
I don't think it will be possible for now. @CyanFish is rewriting the application completely so it would work, on linux, Mac and Windows.

He plan to look at my added features and said he would like to have the same internal image as I have. Maybe he'll add other stuff. I might also fork from this new rewrite, but I am not sure... It took me a while to study the code and understand where was the stuff.
